In [170]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Imputer
from sklearn.model_selection import GridSearchCV , train_test_split , cross_val_score
from sklearn.metrics import classification_report , confusion_matrix


from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, auc
import os
import warnings

In [264]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

id      target           0           1           2           3  \
count  250.000000  250.000000  250.000000  250.000000  250.000000  250.000000   
mean   124.500000    0.640000    0.023292   -0.026872    0.167404    0.001904   
std     72.312977    0.480963    0.998354    1.009314    1.021709    1.011751   
min      0.000000    0.000000   -2.319000   -2.931000   -2.477000   -2.359000   
25%     62.250000    0.000000   -0.644750   -0.739750   -0.425250   -0.686500   
50%    124.500000    1.000000   -0.015500    0.057000    0.184000   -0.016500   
75%    186.750000    1.000000    0.677000    0.620750    0.805000    0.720000   
max    249.000000    1.000000    2.567000    2.419000    3.392000    2.771000   

                4           5           6           7     ...             290  \
count  250.000000  250.000000  250.000000  250.000000     ...      250.000000   
mean     0.001588   -0.007304    0.032052    0.078412     ...        0.044652   
std      1.035411    0.955700    1.006657    0.939731     ...        1.011416   
min     -2.566000   -2.845000   -2.976000   -3.444000     ...       -2.804000   
25%     -0.659000   -0.643750   -0.675000   -0.550750     ...       -0.617000   
50%     -0.023000    0.037500    0.060500    0.183500     ...        0.067500   
75%      0.735000    0.660500    0.783250    0.766250     ...        0.797250   
max      2.901000    2.793000    2.546000    2.846000     ...        2.865000   

              291         292         293         294         295         296  \
count  250.000000  250.000000  250.000000  250.000000  250.000000  250.000000   
mean     0.126344    0.018436   -0.012092   -0.065720   -0.106112    0.046472   
std      0.972567    0.954229    0.960630    1.057414    1.038389    0.967661   
min     -2.443000   -2.757000   -2.466000   -3.287000   -3.072000   -2.634000   
25%     -0.510500   -0.535750   -0.657000   -0.818500   -0.821000   -0.605500   
50%      0.091000    0.057500   -0.021000   -0.009000   -0.079500    0.009500   
75%      0.804250    0.631500    0.650250    0.739500    0.493000    0.683000   
max      2.801000    2.736000    2.596000    2.226000    3.131000    3.236000   

              297         298         299  
count  250.000000  250.000000  250.000000  
mean     0.006452    0.009372   -0.128952  
std      0.998984    1.008099    0.971219  
min     -2.776000   -3.211000   -3.500000  
25%     -0.751250   -0.550000   -0.754250  
50%      0.005500   -0.009000   -0.132500  
75%      0.794250    0.654250    0.503250  
max      2.626000    3.530000    2.771000  

[8 rows x 302 columns]

In [59]:
test.head()

id      0      1      2      3      4      5      6      7      8  ...    \
0  250  0.500 -1.033 -1.595  0.309 -0.714  0.502  0.535 -0.129 -0.687  ...     
1  251  0.776  0.914 -0.494  1.347 -0.867  0.480  0.578 -0.313  0.203  ...     
2  252  1.750  0.509 -0.057  0.835 -0.476  1.428 -0.701 -2.009 -1.378  ...     
3  253 -0.556 -1.855 -0.682  0.578  1.592  0.512 -1.419  0.722  0.511  ...     
4  254  0.754 -0.245  1.173 -1.623  0.009  0.370  0.781 -1.763 -1.432  ...     

     290    291    292    293    294    295    296    297    298    299  
0 -0.088 -2.628 -0.845  2.078 -0.277  2.132  0.609 -0.104  0.312  0.979  
1 -0.683 -0.066  0.025  0.606 -0.353 -1.133 -3.138  0.281 -0.625 -0.761  
2 -0.094  0.351 -0.607 -0.737 -0.031  0.701  0.976  0.135 -1.327  2.463  
3 -0.336 -0.787  0.255 -0.031 -0.836  0.916  2.411  1.053 -1.601 -1.529  
4  2.184 -1.090  0.216  1.186 -0.143  0.322 -0.068 -0.156 -1.153  0.825  

[5 rows x 301 columns]

In [172]:
from sklearn.linear_model import LogisticRegression

X=train.drop(['id','target'],axis=1)
y=train.target

clf2 = LogisticRegression(class_weight='balanced', solver='liblinear', penalty ='l1',C=0.8).fit(X, y)
scores = cross_val_score(clf2, X, y, cv=5)
scores

array([0.7 , 0.72, 0.68, 0.8 , 0.74])

In [191]:
from sklearn.linear_model import SGDClassifier

X=train.drop(['id','target'],axis=1)
y=train.target

clf3 = SGDClassifier(alpha=0.008, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=0.001,
       validation_fraction=0.1, verbose=0, warm_start=False).fit(X, y)
scores = cross_val_score(clf3, X, y, cv=5)
scores

array([0.72, 0.7 , 0.64, 0.76, 0.64])

In [210]:
from sklearn.ensemble import GradientBoostingClassifier

X=train.drop(['id','target'],axis=1)
y=train.target

clf4 = GradientBoostingClassifier(loss='deviance', learning_rate=0.007, n_estimators=200,min_samples_split=2,
                                  validation_fraction=0.1,tol=0.0001).fit(X, y)
scores = cross_val_score(clf4, X, y, cv=5)
scores


array([0.6 , 0.68, 0.7 , 0.7 , 0.7 ])

In [174]:
test_predict= clf3.predict(X)


from sklearn.metrics import classification_report

print(classification_report(y,test_predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        90
         1.0       1.00      1.00      1.00       160

   micro avg       1.00      1.00      1.00       250
   macro avg       1.00      1.00      1.00       250
weighted avg       1.00      1.00      1.00       250



In [211]:
test_predict= 0.5*clf2.predict_proba(test.drop('id',axis=1))[:,1] +  0.2*clf3.predict_proba(test.drop('id',axis=1))[:,1] +0.3*clf4.predict_proba(test.drop('id',axis=1))[:,1]

In [216]:
test_predict=clf3.predict_proba(test.drop('id',axis=1))[:,1]

In [217]:
ss=pd.read_csv('test.csv')
ids = ss['id']

submission_file = open("overfit.csv", "w")

import csv as csv

open_file_object = csv.writer(submission_file)

# Write the header of the csv
open_file_object.writerow(["id","target"])

# Write the rows of the csv
open_file_object.writerows(zip(ids, test_predict))

# Close the file
submission_file.close()

In [237]:
a=[]
for i in train.drop(['id','target'],axis=1).columns:
    
    a.append(train[i].corr(train['target']))
    


In [243]:
d={'col1':a}
d=pd.DataFrame(data=d)


In [249]:
d[d.values<-0.1].index

Int64Index([  4,  16,  39,  43,  63,  73,  80,  82,  90,  91,  98, 108, 117,
            127, 129, 133, 134, 150, 165, 189, 194, 209, 217, 220, 230, 237,
            239, 252, 258, 276, 295, 298],
           dtype='int64')

In [265]:
X=train.drop(['4',  '16',  '39',  '43',  '63',  '73',  '80',  '82',  '90',  '91',  '98', '108', '117',
            '127', '129', '133', '134', '150', '165', '189', '194', '209', '217', '220', '230', '237',
            '239', '252', '258', '276', '295', '298'],axis=1)

N_test=test.drop(['4',  '16',  '39',  '43',  '63',  '73',  '80',  '82',  '90',  '91',  '98', '108', '117',
            '127', '129', '133', '134', '150', '165', '189', '194', '209', '217', '220', '230', '237',
            '239', '252', '258', '276', '295', '298'],axis=1)
y=X.target

In [307]:
from sklearn.linear_model import LogisticRegression


#X=X.drop(['id','target'],axis=1)


clf2 = LogisticRegression(class_weight='balanced', solver='liblinear', penalty ='l1',C=0.122).fit(X, y)
scores = cross_val_score(clf2, X, y, cv=5)
scores

array([0.68, 0.66, 0.66, 0.6 , 0.6 ])

In [276]:
from sklearn.ensemble import GradientBoostingClassifier



clf4 = GradientBoostingClassifier(loss='deviance', learning_rate=0.0042, n_estimators=200,min_samples_split=2,
                                  validation_fraction=0.1,tol=0.0001).fit(X, y)
scores = cross_val_score(clf4, X, y, cv=5)
scores

array([0.64, 0.66, 0.68, 0.72, 0.7 ])

In [295]:
from sklearn.linear_model import SGDClassifier



clf3 = SGDClassifier(alpha=0.0092, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=0.001,
       validation_fraction=0.1, verbose=0, warm_start=False).fit(X, y)
scores = cross_val_score(clf3, X, y, cv=5)
scores

array([0.62, 0.6 , 0.58, 0.72, 0.6 ])

In [299]:
test_predict= clf2.predict_proba(N_test.drop('id',axis=1))[:,1] 

In [300]:
ss=pd.read_csv('test.csv')
ids = ss['id']

submission_file = open("overfit.csv", "w")

import csv as csv

open_file_object = csv.writer(submission_file)

# Write the header of the csv
open_file_object.writerow(["id","target"])

# Write the rows of the csv
open_file_object.writerows(zip(ids, test_predict))

# Close the file
submission_file.close()